name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Commands
      shell: bash
      run: |
        dpkg --version
        sudo dpkg --add-architecture i386
        #sudo apt-get update -y -qq
        #sudo apt-get install -y -qq devscripts gcc-i686-linux-gnu lib32z1 libc6-i386 xdg-utils
        #export LD_LIBRARY_PATH="/usr/lib/i386-linux-gnu"
        dpkg --print-architecture
        cat  << 'EOF' >> ~/.bashrc
        
        # Override dpkg
        function dpkg() {
        if [ "$1" = "--print-architecture" ] ; then
          command echo "i386"
        else
          command dpkg "$@"
        fi
        }
        EOF
        source ~/.bashrc
        dpkg --print-architecture
        
    - name: test
      run: |
        source ~/.bashrc
        dpkg --print-architecture
        cat ~/.bashrc
      
    - name: environment
      run: |
        echo $ENV
        echo "export ENV=DEV" > ~/.bashrc
        source ~/.bashrc
        echo $ENV
    - name: get_env
      run: | 
        source ~/.bashrc
        echo $ENV

 
