name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Commands
      shell: bash
      run: |
        dpkg --version
        sudo dpkg --add-architecture i386
        #sudo apt-get update -y -qq
        #sudo apt-get install -y -qq devscripts gcc-i686-linux-gnu lib32z1 libc6-i386 xdg-utils
        #export LD_LIBRARY_PATH="/usr/lib/i386-linux-gnu"

        cat  << 'EOF' > dpkg.bash
        #!/bin/bash
        if [ "$1" = "--print-architecture" ] ; then
          command echo "i386"
        else
          command dpkg2 "$@"
        fi
        EOF

        DPKGDIR=$(dirname -- "$(which dpkg)")
        dpkg --print-architecture
        sudo mv ${DPKGDIR}/dpkg ${DPKGDIR}/dpkg2
        sudo cp dpkg.bash ${DPKGDIR}/dpkg
        sudo chmod --reference=${DPKGDIR}/dpkg2 ${DPKGDIR}/dpkg

        dpkg --print-architecture
        
        source ~/.bashrc
        dpkg --print-architecture
        
    - name: test
      run: |
        dpkg --print-architecture
      

 
