name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Commands
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        #sudo apt-get update -y -qq
        #sudo apt-get install -y -qq devscripts gcc-i686-linux-gnu lib32z1 libc6-i386 xdg-utils
        #export LD_LIBRARY_PATH="/usr/lib/i386-linux-gnu"
        dpkg --print-architecture
        dpkg --version
        dpkg --target-arch i386
        dpkg --print-architecture
        dpkg --match-bits 32
        dpkg --print-architecture
      


 
